#!/usr/bin/env python3
"""
Script to fix YouTube cookies issues
"""
import os
import sys
from config import Config

def check_and_fix_cookies():
    """Check and fix cookies file"""
    if not os.path.exists(Config.COOKIES_FILE):
        print(f"❌ Cookies file not found: {Config.COOKIES_FILE}")
        return False
    
    with open(Config.COOKIES_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"📊 Cookies file size: {len(content)} bytes")
    
    # Check for common issues
    issues = []
    
    if not content.strip():
        issues.append("File is empty")
    
    if "# HTTP Cookie File" not in content and "# Netscape HTTP Cookie File" not in content:
        issues.append("Missing Netscape format header")
    
    if ".youtube.com" not in content.lower():
        issues.append("No YouTube domain cookies found")
    
    if issues:
        print("⚠️ Issues found:")
        for issue in issues:
            print(f"  - {issue}")
        
        # Try to fix by downloading from COOKIE_URL
        if Config.COOKIE_URL:
            print(f"\n🔄 Downloading fresh cookies from: {Config.COOKIE_URL}")
            # Import the function
            from main import YouTubeDownloaderBot
            bot = YouTubeDownloaderBot(None)
            
            import asyncio
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            success = loop.run_until_complete(bot.download_cookies_from_url(Config.COOKIE_URL))
            
            if success:
                print("✅ Cookies updated successfully")
                return True
            else:
                print("❌ Failed to download cookies")
                return False
        else:
            print("❌ COOKIE_URL not set, cannot download fresh cookies")
            return False
    else:
        print("✅ Cookies file looks good")
        return True

def create_test_cookies():
    """Create a test cookies file"""
    print("🧪 Creating test cookies file...")
    
    test_cookies = """# Netscape HTTP Cookie File
# This file was generated by yt-dlp
# https://github.com/yt-dlp/yt-dlp

.youtube.com	TRUE	/	TRUE	2147483647	VISITOR_INFO1_LIVE	YOUR_COOKIE_VALUE_HERE
.youtube.com	TRUE	/	TRUE	2147483647	LOGIN_INFO	YOUR_COOKIE_VALUE_HERE
.youtube.com	TRUE	/	TRUE	2147483647	PREF	f1=50000000
.youtube.com	TRUE	/	TRUE	2147483647	YSC	YOUR_COOKIE_VALUE_HERE
.youtube.com	TRUE	/	TRUE	2147483647	GPS	1
"""
    
    with open(Config.COOKIES_FILE, 'w', encoding='utf-8') as f:
        f.write(test_cookies)
    
    print(f"📁 Test cookies file created: {Config.COOKIES_FILE}")
    print("⚠️ Note: You need to replace YOUR_COOKIE_VALUE_HERE with actual cookie values")

if __name__ == "__main__":
    print("🔧 YouTube Cookies Fixer")
    print("=" * 50)
    
    if len(sys.argv) > 1 and sys.argv[1] == "--create-test":
        create_test_cookies()
    else:
        check_and_fix_cookies()
